// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNQEa_xZEqWSFozpoHK5Z3FAiIuiyNRQs',
    appId: '1:834175067279:web:a9865537a51641cb423cfa',
    messagingSenderId: '834175067279',
    projectId: 'shortcak-es',
    authDomain: 'shortcak-es.firebaseapp.com',
    storageBucket: 'shortcak-es.firebasestorage.app',
    measurementId: 'G-YWPJQFC839',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbsuNUC-XMcQWdgTGu98rxef85YrqGbu4',
    appId: '1:834175067279:android:74cd2ee30dfcdd83423cfa',
    messagingSenderId: '834175067279',
    projectId: 'shortcak-es',
    storageBucket: 'shortcak-es.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMoi7qBCzb7wyh3uJKCWaiqzqiVcSuMqM',
    appId: '1:834175067279:ios:2fd65ebcbf68612b423cfa',
    messagingSenderId: '834175067279',
    projectId: 'shortcak-es',
    storageBucket: 'shortcak-es.firebasestorage.app',
    iosClientId: '834175067279-m1bdmnf8dg9cvannc7ls7hinpo3j7gkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMoi7qBCzb7wyh3uJKCWaiqzqiVcSuMqM',
    appId: '1:834175067279:ios:2fd65ebcbf68612b423cfa',
    messagingSenderId: '834175067279',
    projectId: 'shortcak-es',
    storageBucket: 'shortcak-es.firebasestorage.app',
    iosClientId: '834175067279-m1bdmnf8dg9cvannc7ls7hinpo3j7gkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNQEa_xZEqWSFozpoHK5Z3FAiIuiyNRQs',
    appId: '1:834175067279:web:702a46a1f952f5c3423cfa',
    messagingSenderId: '834175067279',
    projectId: 'shortcak-es',
    authDomain: 'shortcak-es.firebaseapp.com',
    storageBucket: 'shortcak-es.firebasestorage.app',
    measurementId: 'G-KGFYD8FZYP',
  );
}
